# Generated by Django 5.2.6 on 2025-10-09 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タスク名')),
                ('description', models.TextField(blank=True, verbose_name='詳細')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='期限日')),
                ('is_completed', models.BooleanField(default=False, verbose_name='完了フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': 'TODO',
                'verbose_name_plural': 'TODOs',
                'ordering': ['-created_at'],
            },
        ),
    ]
