# Generated by Django 5.2.6 on 2025-10-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work09', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='期限日'),
        ),
    ]
